### ISSUE TITLE
wipe_db_on_cookie_change deletes all data every puppet run

### ISSUE THREAD

**Issue by mattboston** [voxpupuli/puppet-rabbitmq#153]
When using wipe_db_on_cookie_change, even if the cookie hasn't changed, every 30 minutes Puppet runs the exec wipe_db and all my data is lost.
```puppet
 class { 'rabbitmq':
   version                  => "${rabbitmq_version}",
   config_cluster           => true,
   cluster_nodes            => [ "${rabbitmq_node1}", "${rabbitmq_node2}" ],
   cluster_node_type        => 'disc',
   erlang_cookie            => "${erlang_cookie}",
   wipe_db_on_cookie_change => true,
}
```

**Comment by wyardley** [comment]
Ancient ticket, but seems like this must already have been fixed:
```
[root@centos-7-x64 ~]# puppet apply /tmp/153
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/rabbitmq/manifests/init.pp", 276]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Notice: Compiled catalog for centos-7-x64.axsops.net in environment production in 0.53 seconds
Notice: /Stage[main]/Rabbitmq::Config/Rabbitmq_erlang_cookie[/var/lib/rabbitmq/.erlang.cookie]/content: The rabbitmq erlang cookie was changed
Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq.config]/content: content changed '{md5}9e960c789346c36bb61a5274bc6954de' to '{md5}cf38a8109147e19fc94f7622353cb296'
Notice: /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 2.18 seconds
[root@centos-7-x64 ~]# puppet apply /tmp/153
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/rabbitmq/manifests/init.pp", 276]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Notice: Compiled catalog for centos-7-x64.axsops.net in environment production in 0.53 seconds
Notice: Applied catalog in 0.41 seconds
[root@centos-7-x64 ~]# cat /tmp/153 
 class { 'rabbitmq':
   config_cluster           => true,
   cluster_nodes            => [ "number1", "number2" ],
   cluster_node_type        => 'disc',
   erlang_cookie            => "A123456",
   wipe_db_on_cookie_change => true,
}
```
