### ISSUE TITLE
unexpected token at 'arguments'

### ISSUE THREAD

**Issue by spafe** [voxpupuli/puppet-rabbitmq#772]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
puppetserver-5.1.0-1.el6
puppet-agent-5.2.0-1.el6
- Ruby: ruby 2.4
- Distribution: CentOS release 6.6
- Module version: 9.0.0

## How to reproduce (e.g Puppet code you use)
   ~> rabbitmq_policy { 'ha-all-dummy@/':
    pattern    => '^dummy\.',
    priority   => 0,
    applyto    => 'queues',
    definition => {
      'ha-mode'      => 'all',
    },
   }

## What are you seeing
Info: Applying configuration version ********_rabbitmq-64d686ac193'
**Error: Failed to apply catalog: 743: unexpected token at 'arguments'**

## What behavior did you expect instead
Puppet run should be clean and apply the catalog successfully. 

## Output log (With Debug and Trace)
Debug: Executing: '/usr/sbin/rabbitmq-plugins list -E -m'
Debug: Command succeeded
Debug: Executing: '/sbin/service rabbitmq-server status'
Debug: Executing: '/sbin/chkconfig rabbitmq-server'
Debug: Prefetching rabbitmqadmin resources for rabbitmq_queue
Debug: Executing: '/usr/sbin/rabbitmqctl list_vhosts -q'
Debug: Executing: '/usr/sbin/rabbitmqctl list_queues -q -p name name durable auto_delete arguments'
Debug: Executing: '/usr/sbin/rabbitmqctl list_queues -q -p / name durable auto_delete arguments'
Debug: Storing state
Debug: Stored state in 0.09 seconds
Error: Failed to apply catalog: 743: unexpected token at 'arguments'
/opt/puppetlabs/puppet/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/opt/puppetlabs/puppet/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:49:in `block (2 levels) in instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:36:in `map'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:36:in `block in instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:35:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:35:in `instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:60:in `prefetch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:340:in `prefetch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:241:in `prefetch_if_necessary'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:107:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:119:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:169:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:225:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:140:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:224:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:172:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:224:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:344:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:222:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:263:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:196:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:46:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:46:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:110:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:43:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:67:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:42:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:40:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:365:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:343:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:666:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Debug: Dynamically-bound server lookup failed, falling back to report_server setting

## Any additional information you'd like to impart
**Rabbitmq Version:** 3.7.9
**Erlang:** 21.1

**Comment by spafe** [comment]
Sorry for creating a duplicate issue.
